language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
  - npm install

install:
  - hexo clean
  - hexo generate

script:
  - hexo lc-counter register $LC_USERNAME $LC_PASSWORD
  - git config user.name "Ayase-252"
  - git config user.email "bitdqy@hotmail.com"
  - sed -i "s/ACCESS_TOKEN/${ACCESS_TOKEN}/g" ./_config.yml
  - hexo deploy