language: node_js
node_js:
  - '10'

cache: npm

before_install:
  - npm install -g hexo-cli
  - npm install
  # Install external plugin for hexo-next theme
  - cd themes/next-reloaded
  - git clone https://github.com/theme-next/theme-next-reading-progress source/lib/reading_progress
  - git clone https://github.com/theme-next/theme-next-quicklink.git source/lib/quicklink
  - cd ../..

install:
  - hexo clean
  - hexo generate

script:
  - git config user.name "Ayase-252"
  - git config user.email "bitdqy@hotmail.com"
  - sed -i "s/ACCESS_TOKEN/${ACCESS_TOKEN}/g" ./_config.yml
  # - sed -i "s/LC_USERNAME/${LC_USERNAME}/g" ./_config.yml
  # - sed -i "s/LC_PASSWORD/${LC_PASSWORD}/g" ./_config.yml
  - hexo deploy
