language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
  - npm install

install:
  - hexo clean --config source/_data/next.yml
  - hexo generate --config source/_data/next.yml

script:
  - git config user.name "Ayase-252"
  - git config user.email "bitdqy@hotmail.com"
  - sed -i "s/ACCESS_TOKEN/${ACCESS_TOKEN}/g" ./source/_data/next.yml
  - hexo deploy --config source/_data/next.yml