# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install Hexo
      run: npm i -g hexo-cli
    - name: Install Dependencies
      run: yarn
    - name: Build Static Files
      run: |
        hexo clean
        hexo generate
    - name: Publish
      run: |
        git config --global user.name "Ayase-252"
        git config --global user.email "bitdqy@hotmail.com"
        sed -i "s/ACCESS_TOKEN/${{ secrets.PUBLISH_TOKEN }}/g" ./_config.yml
        hexo deploy
